In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/netflix_titles_nov_2019.csv')
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show

In [4]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5837 non-null   int64
 1   title         5837 non-null   object
 2   director      3936 non-null   object
 3   cast          5281 non-null   object
 4   country       5410 non-null   object
 5   date_added    5195 non-null   object
 6   release_year  5837 non-null   int64
 7   rating        5827 non-null   object
 8   duration      5837 non-null   object
 9   listed_in     5837 non-null   object
 10  description   5837 non-null   object
 11  type          5837 non-null   object
dtypes: int64(2), object(10)
memory usage: 547.3+ KB

In [5]:
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], format='%B %d, %Y', errors='coerce')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5837 non-null   int64
 1   title         5837 non-null   object
 2   director      3936 non-null   object
 3   cast          5281 non-null   object
 4   country       5410 non-null   object
 5   date_added    5195 non-null   datetime64[ns]
 6   release_year  5837 non-null   int64
 7   rating        5827 non-null   object
 8   duration      5837 non-null   object
 9   listed_in     5837 non-null   object
 10  description   5837 non-null   object
 11  type          5837 non-null   object
dtypes: datetime64[ns](1), int64(2), object(9)
memory usage: 547.3+ KB

In [9]:
df.isnull().sum()

show_id            0
title              0
director        1901
cast             556
country          427
date_added       642
release_year       0
rating            10
duration           0
listed_in          0
description        0
type               0
dtype: int64

In [10]:
df = df.dropna(subset = ["date_added", "duration"])
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['cast'] = df['cast'].fillna('No data')
df['director'] = df['director'].fillna("Incomplete Data")

In [11]:
df.isnull().sum()

show_id         0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          9
duration        0
listed_in       0
description     0
type            0
dtype: int64

In [12]:


df = df.rename(columns={'listed_in':'Genres'})
df['Genres'] = df['Genres'].apply(lambda s: s.split(",")[0])
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,Genres,description,type
0,81193313,Chocolate,Incomplete Data,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,2019-11-30,2019,TV-14,1 Season,International TV Shows,Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,United States,2019-11-30,2019,TV-G,67 min,Documentaries,"From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,2019-11-30,2019,TV-14,135 min,Comedies,A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium",2019-11-29,2019,TV-14,106 min,Dramas,"Arranged to marry a rich man, young Ada is cru...",Movie
5,81172754,Crazy people,Moses Inwang,"Ramsey Nouah, Chigul, Sola Sobowale, Ireti Doy...",Nigeria,2019-11-29,2018,TV-14,107 min,Comedies,Nollywood star Ramsey Nouah learns that someon...,Movie

# **1. What is the ratio of tv shows and movies added in netflix?**

In [13]:


df['type'].value_counts()

type
Movie      3938
TV Show    1257
Name: count, dtype: int64

In [14]:
fig = px.pie(df, names='type', title="Netflix Content Distribution", hole=0.5)
fig.show()

In [15]:
x = df.groupby('type')['type'].apply(lambda s: round(len(s) / len(df), 2))
ratio = pd.DataFrame(x).T
ratio

type  Movie  TV Show
type   0.76     0.24

In [16]:
fig = px.bar(x=ratio.columns,
             y=ratio.values.flatten(),
             title="Ratio of Movies and TV Shows")
fig.update_xaxes(title_text="Type")
fig.update_yaxes(title_text="Percentage")
fig.show()


# 2. Which country has produced more Movies and TV shows?**bold text**

In [17]:


netflix_movies = df[df['type']=="Movie"]
netflix_tv_shows = df[df['type']=="TV Show"]

In [18]:
netflix_movies.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,Genres,description,type
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,United States,2019-11-30,2019,TV-G,67 min,Documentaries,"From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,2019-11-30,2019,TV-14,135 min,Comedies,A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium",2019-11-29,2019,TV-14,106 min,Dramas,"Arranged to marry a rich man, young Ada is cru...",Movie
5,81172754,Crazy people,Moses Inwang,"Ramsey Nouah, Chigul, Sola Sobowale, Ireti Doy...",Nigeria,2019-11-29,2018,TV-14,107 min,Comedies,Nollywood star Ramsey Nouah learns that someon...,Movie
6,81120982,I Lost My Body,Jérémy Clapin,"Hakim Faris, Victoire Du Bois, Patrick d'Assum...",France,2019-11-29,2019,TV-MA,81 min,Dramas,"Romance, mystery and adventure intertwine as a...",Movie

In [19]:
max_movies_country = netflix_movies['country'].value_counts().head(10)
max_movies_country

country
United States     1544
India              645
United Kingdom     162
Canada              87
Spain               78
Turkey              55
Mexico              51
Hong Kong           49
France              48
Japan               44
Name: count, dtype: int64

In [20]:
fig = px.bar(x=max_movies_country.index,
             y=max_movies_country.values,
             title="Country that has produced more Movies")
fig.update_xaxes(title_text='Country')
fig.update_yaxes(title_text='Count')
fig.show()

In [21]:
max_tv_shows_country = netflix_tv_shows["country"].value_counts().head(10)
max_tv_shows_country

country
United States     496
United Kingdom    108
South Korea        87
Japan              79
Taiwan             64
India              48
France             30
China              26
Mexico             25
Australia          22
Name: count, dtype: int64

In [22]:
fig = px.bar(x=max_tv_shows_country.index,
             y=max_tv_shows_country.values,
             title="Country that has produced more TV Shows")
fig.update_xaxes(title_text='Country')
fig.update_yaxes(title_text='Count')
fig.show()